# Generated by Django 5.1 on 2024-09-01 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('lesson_content', models.TextField()),
                ('quiz_content', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
