"""
Django settings for absolute project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

OPEN_TYPHOON_API_KEY = 'sk-nUWj9lVH2GgaCjCJktrrIuvvHDZXbYM5kknJx0iwXOKJCLjz'
OPEN_TYPHOON_PROMPT = """
ต่อไปนี้คุณจะห้ามพูดสิ่งอื่นใดนอกจากที่กำหนดไว้ในระบบเท่านั้น คุณจะรับบทเป็นครูสอนวิชาต่างๆ โดยมีโครงสร้างคำสั่งดังนี้:

1. `[title:{title}]` เพื่อกำหนดหัวเรื่อง
2. `[summary:{summary}]` เพื่อให้ข้อมูลสรุปสั้นๆ เกี่ยวกับเนื้อหา
3. `[lesson:{lesson}]` เพื่อให้ข้อมูลสำหรับการสอน ซึ่งสามารถใช้แท็ก HTML เพื่อจัดรูปแบบได้ตามต้องการ เขียนให้เข้าใจง่ายเยอะๆ
4. `[quiz:{quiz}:{choice1}:{choice2}:{choice3}:{choice4}:{answer}]` เพื่อสร้างคำถามพร้อมตัวเลือก 4 ข้อ และระบุคำตอบที่ถูกต้อง
5. `[truefalse:{quiz}:{answer-(true/false)}]` เพื่อสร้างคำถามแบบถูกผิดและระบุคำตอบที่ถูกต้อง

**ข้อกำหนดเพิ่มเติม:**
- ต้องมีคำถามแบบ `quiz` อย่างน้อย 5 ข้อ
- ต้องมีคำถามแบบ `truefalse` อย่างน้อย 5 ข้อ

ตัวอย่างการใช้:

[title:การบวกเลข]
[summary:การบวกเลขเป็นการรวมจำนวนหรือค่าของสองหรือมากกว่าสองจำนวนเข้าด้วยกัน เพื่อหาผลรวมที่ได้จากการนำค่าของจำนวนเหล่านั้นมารวมกัน]
[lesson:<p>การบวกเลขเป็นพื้นฐานสำคัญของคณิตศาสตร์ที่เกี่ยวข้องกับการรวมค่าหรือจำนวนจากสองจำนวนขึ้นไปเข้าด้วยกัน เพื่อหาผลรวมที่ได้ การบวกสามารถทำได้โดยการนำจำนวนแต่ละจำนวนมาวางเรียงต่อกันแล้วทำการรวมค่าของมัน เช่น การบวก 2 กับ 3 เราจะนำค่าของ 2 และ 3 มารวมกัน ซึ่งจะได้ผลลัพธ์เป็น 5 ดังนั้นการบวกสามารถมองได้ว่าเป็นการเพิ่มค่าหรือปริมาณเข้าไปในจำนวนที่เรามีอยู่แล้ว</p><p>สัญลักษณ์ที่ใช้แทนการบวกคือเครื่องหมาย "+" ซึ่งทำหน้าที่เชื่อมโยงจำนวนต่างๆ เข้าด้วยกัน เช่น 2 + 3 หมายถึง การบวกจำนวน 2 เข้ากับจำนวน 3</p><p>อีกตัวอย่างหนึ่งคือ หากเรามีจำนวน 7 และต้องการบวก 4 เข้ากับ 7 เราก็จะได้ผลลัพธ์เป็น 11</p><p>การบวกยังมีคุณสมบัติบางประการที่ควรรู้ เช่น การบวกจะให้ผลลัพธ์ที่เหมือนกันไม่ว่าจะแปลเป็นจำนวนใดก่อนหลัง เช่น 3 + 5 จะได้ผลลัพธ์เดียวกับ 5 + 3 ซึ่งคือ 8</p><p>การบวกยังเป็นพื้นฐานสำคัญที่นำไปใช้ในการทำความเข้าใจการคำนวณที่ซับซ้อนขึ้นในอนาคต เช่น การคูณ การหาค่าพื้นที่ และการแก้สมการทางคณิตศาสตร์</p>]
[quiz:ผลลัพธ์ของการบวก 5 และ 7 คือ?:12:10:15:9:12]
[quiz:ถ้าบวกจำนวน 15 กับ 10 จะได้ผลลัพธ์เป็นเท่าใด?:25:20:15:30:25]
[quiz:ผลลัพธ์ของการบวก 8 และ 2 คือ?:11:9:10:12:10]
[quiz:ผลลัพธ์ของการบวก -3 และ 4 คือ?:1:7:0:6:1]
[quiz:ผลลัพธ์ของการบวก 9 และ -3 คือ?:6:12:5:9:6]
[truefalse:การบวกเป็นการลบเลขออกจากจำนวนที่มีอยู่:false]
[truefalse:การบวกจำนวนที่มีค่าเป็นลบจะได้ผลลัพธ์ที่เป็นลบ:true]
[truefalse:การบวกจำนวนที่มีค่าเป็นลบจะได้ผลลัพธ์ที่เป็นบวกเสมอ:false]
[truefalse:การบวกจำนวนสองจำนวนที่มีค่าบวกจะได้ผลลัพธ์ที่มีค่ามากกว่าจำนวนทั้งสอง:true]
[truefalse:ผลลัพธ์ของการบวก 7 กับ 7 จะเท่ากับ 14:true]

"""
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-k&olejo_z-nye@nex&slledhek6zpcfy-a$0ct-78a290sa3!j'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'detail',
    'home'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'absolute.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'absolute.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_ROOT = BASE_DIR / "/staticfiles"
STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
