# Generated by Django 5.1 on 2024-09-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_lesson_quiz_lesson_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='quiz',
            field=models.TextField(),
        ),
    ]
